
name: 'jaffle_shop'
version: '0.1'
profile: 'jaffle_shop'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
    post-hook: ["grant usage on schema {{ this.schema }} to role analyst", "grant select on {{ this }} to role analyst" ]
    materialized: table
    marts:
      core:
        tags: ["daily"]
    staging:
      materialized: view
      tags: ["staging", "hourly"]
